site_name: GCES - OWASP

nav:
  - Home: index.md
  - Sprints:
      - Sprint 0: sprints/0.md
      - Sprint 1: sprints/1.md
      - Sprint 2: sprints/2.md
      - Sprint 3: sprints/3.md
      - Sprint 4: sprints/4.md
  - Estudo Blue Team:
      - CI/CD: estudo/ci-cd.md
      - Ferramentas de segurança: estudo/ferramentas.md
  - Diários:
      - Guilherme Peixoto (170034941):
          - Sprint 0: diarios/170034941/0.md
          - Sprint 1: diarios/170034941/1.md
          - Sprint 2: diarios/170034941/2.md
          - Sprint 3: diarios/170034941/3.md
      - Sebastian Zuzunaga (211006957):
          - Sprint 0: diarios/211006957/0.md
      - Mateus Vieira (221008703):
          - Sprint 0: diarios/221008703/0.md
          - Sprint 1: diarios/221008703/1.md
          - Sprint 2: diarios/221008703/2.md
          - Sprint 3: diarios/221008703/3.md
          - Sprint 4: diarios/221008703/4.md
      - Júlio Costa (211031744):
          - Sprint 0: diarios/211031744/0.md
          - Sprint 1: diarios/211031744/1.md
          - Sprint 2: diarios/211031744/2.md
          - Sprint 3: diarios/211031744/3.md
          - Sprint 4: diarios/211031744/4.md
      - Marcus Vinicius (211031403):
          - Sprint 0: diarios/211031403/Sprint-0.md
          - Sprint 1: diarios/211031403/Sprint 1.md
          - Sprint 2: diarios/211031403/Sprint-2.md
          - Sprint 3: diarios/211031403/sprint-3.md  
          - Sprint 4: diarios/211031403/Sprint-4.md
      - Breno Lucena (202017343):
          - Sprint 0: diarios/202017343/202017343.md
          - Sprint 1: diarios/202017343/1.md
          - Sprint 2: diarios/202017343/2.md
          - Sprint 3: diarios/202017343/3.md
      - Henrique Hida (180113569):
          - Sprint 0: diarios/180113569/0.md
          - Sprint 1: diarios/180113569/1.md
          - Sprint 2: diarios/180113569/2.md
      - Daniel Rocha Oliveira (190104821):
          - Sprint 0: diarios/190104821/sprint_0_diario.md
          - Sprint 1: diarios/190104821/sprint_1_diario.md
          - Sprint 2: diarios/190104821/sprint_2_diario.md
          - Sprint 3: diarios/190104821/sprint_3_diario.md
          - Sprint 4: diarios/190104821/sprint_4_diario.md
      - Henrique Camelo Quenino (221008098):
          - Sprint 0: diarios/221008098/0.md
          - Sprint 1: diarios/221008098/1.md
          - Sprint 2: diarios/221008098/2.md
      - Ana Carolina Fialho (221031102):
          - Sprint 0: diarios/221031102/0.md
          - Sprint 1: diarios/221031102/1.md
          - Sprint 2: diarios/221031102/2.md
          - Sprint 3: diarios/221031102/03.md
      - Miguel Arthur Oliveira de Lima (211062320):
          - Sprint 0: diarios/211062320/0.md
          - Sprint 1: diarios/211062320/01.md
          - Sprint 2: diarios/211062320/02.md
          - Sprint 3: diarios/211062320/03.md
          - Sprint 4: diarios/211062320/04.md
    


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
